using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.ScheduleDetails;

namespace FaceAPI.ScheduleDetails
{
    public class ScheduleDetailsAppService : ScheduleDetailsAppServiceBase, IScheduleDetailsAppService
    {
        //<suite-custom-code-autogenerated>
        public ScheduleDetailsAppService(IScheduleDetailRepository scheduleDetailRepository, ScheduleDetailManager scheduleDetailManager, IRepository<ScheduleFormat, Guid> scheduleFormatRepository)
            : base(scheduleDetailRepository, scheduleDetailManager, scheduleFormatRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}