using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Staffs;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Staffs;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Staffs;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Staffs;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Staffs;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Schedules;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using FaceAPI.Shared;

namespace FaceAPI.Schedules
{
    public class SchedulesAppService : SchedulesAppServiceBase, ISchedulesAppService
    {
        //<suite-custom-code-autogenerated>
        public SchedulesAppService(IScheduleRepository scheduleRepository, ScheduleManager scheduleManager, IDistributedCache<ScheduleExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Staff, Guid> staffRepository, IRepository<ScheduleDetail, Guid> scheduleDetailRepository)
            : base(scheduleRepository, scheduleManager, excelDownloadTokenCache, staffRepository, scheduleDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}