using FaceAPI.Shared;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Salaries;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using FaceAPI.Shared;

namespace FaceAPI.Salaries
{
    public class SalariesAppService : SalariesAppServiceBase, ISalariesAppService
    {
        //<suite-custom-code-autogenerated>
        public SalariesAppService(ISalaryRepository salaryRepository, SalaryManager salaryManager, IDistributedCache<SalaryExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Department, Guid> departmentRepository)
            : base(salaryRepository, salaryManager, excelDownloadTokenCache, departmentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}