using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Salaries;
using Volo.Abp.Caching;

namespace FaceAPI.Salaries
{
    public class SalariesAppService : SalariesAppServiceBase, ISalariesAppService
    {
        //<suite-custom-code-autogenerated>
        public SalariesAppService(ISalaryRepository salaryRepository, SalaryManager salaryManager, IDistributedCache<SalaryExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Department, Guid> departmentRepository, IRepository<Title, Guid> titleRepository)
            : base(salaryRepository, salaryManager, excelDownloadTokenCache, departmentRepository, titleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}