using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleFormats;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.ScheduleDetails;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.Timesheets
{
    public class Timesheet : TimesheetBase
    {
        //<suite-custom-code-autogenerated>
        protected Timesheet()
        {

        }

        public Timesheet(Guid id, Guid? scheduleId, Guid? scheduleDetailId, Guid? scheduleFormatId, DateTime timeIn, DateTime timeOut, int hoursWork, string? code = null, string? note = null)
            : base(id, scheduleId, scheduleDetailId, scheduleFormatId, timeIn, timeOut, hoursWork, code, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}