using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Timesheets
{
    public class TimesheetManager : TimesheetManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TimesheetManager(ITimesheetRepository timesheetRepository)
            : base(timesheetRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}