using FaceAPI.Shared;
using FaceAPI.Timesheets;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Timesheets;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Timesheets;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Timesheets;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Shared;
using FaceAPI.Timesheets;
using FaceAPI.Titles;
using FaceAPI.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Staffs;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using FaceAPI.Shared;

namespace FaceAPI.Staffs
{
    public class StaffsAppService : StaffsAppServiceBase, IStaffsAppService
    {
        //<suite-custom-code-autogenerated>
        public StaffsAppService(IStaffRepository staffRepository, StaffManager staffManager, IDistributedCache<StaffExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Department, Guid> departmentRepository, IRepository<Title, Guid> titleRepository, IRepository<Timesheet, Guid> timesheetRepository)
            : base(staffRepository, staffManager, excelDownloadTokenCache, departmentRepository, titleRepository, timesheetRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}