using FaceAPI.Timesheets;
using FaceAPI.Timesheets;
using FaceAPI.Timesheets;
using FaceAPI.Timesheets;
using FaceAPI.Timesheets;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Staffs
{
    public class StaffManager : StaffManagerBase
    {
        //<suite-custom-code-autogenerated>
        public StaffManager(IStaffRepository staffRepository,
        IRepository<Timesheet, Guid> timesheetRepository)
            : base(staffRepository, timesheetRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}