using FaceAPI.Shared;
using FaceAPI.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Positions;

namespace FaceAPI.Positions
{
    public class PositionsAppService : PositionsAppServiceBase, IPositionsAppService
    {
        //<suite-custom-code-autogenerated>
        public PositionsAppService(IPositionRepository positionRepository, PositionManager positionManager, IRepository<Department, Guid> departmentRepository)
            : base(positionRepository, positionManager, departmentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}