using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Titles;

namespace FaceAPI.Titles
{
    public class TitlesAppService : TitlesAppServiceBase, ITitlesAppService
    {
        //<suite-custom-code-autogenerated>
        public TitlesAppService(ITitleRepository titleRepository, TitleManager titleManager)
            : base(titleRepository, titleManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}