using FaceAPI.Staffs;
using FaceAPI.Staffs;
using FaceAPI.Staffs;
using FaceAPI.Staffs;
using FaceAPI.Staffs;
using FaceAPI.Departments;
using FaceAPI.Departments;
using FaceAPI.Departments;
using FaceAPI.Departments;
using FaceAPI.Departments;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.Schedules
{
    public class Schedule : ScheduleBase
    {
        //<suite-custom-code-autogenerated>
        protected Schedule()
        {

        }

        public Schedule(Guid id, Guid staffId, DateTime dateFrom, DateTime dateTo, string? code = null, string? name = null, string? note = null)
            : base(id, staffId, dateFrom, dateTo, code, name, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}