using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using FaceAPI.ScheduleDetails;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Schedules
{
    public class ScheduleManager : ScheduleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ScheduleManager(IScheduleRepository scheduleRepository,
        IRepository<ScheduleDetail, Guid> scheduleDetailRepository)
            : base(scheduleRepository, scheduleDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}