using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.Titles
{
    public class Title : TitleBase
    {
        //<suite-custom-code-autogenerated>
        protected Title()
        {

        }

        public Title(Guid id, string? code = null, string? name = null, string? note = null)
            : base(id, code, name, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}