using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Titles
{
    public class TitleManager : TitleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TitleManager(ITitleRepository titleRepository)
            : base(titleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}