using FaceAPI.Departments;
using FaceAPI.Departments;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Salaries
{
    public class SalaryManager : SalaryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SalaryManager(ISalaryRepository salaryRepository,
        IRepository<Department, Guid> departmentRepository)
            : base(salaryRepository, departmentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}