using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.Salaries
{
    public class SalaryManager : SalaryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SalaryManager(ISalaryRepository salaryRepository)
            : base(salaryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}