using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.Salaries
{
    public class Salary : SalaryBase
    {
        //<suite-custom-code-autogenerated>
        protected Salary(Guid guid)
        {

        }

        public Salary(Guid id, double allowance, double basic, double bonus, string? code = null)
            : base(id, allowance, basic, bonus, code)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}