using FaceAPI.Departments;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Titles;
using FaceAPI.Departments;
using FaceAPI.Titles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FaceAPI.Salaries
{
    public class Salary : SalaryBase
    {
        protected Salary()
        {

        }
        public Salary(Guid id, Guid? departmentId, Guid? titleId, double allowance, double basic, double bonus, string? code = null)
            : base(id, departmentId, titleId, allowance, basic, bonus, code)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}