using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.Departments
{
    public class Department : DepartmentBase
    {
        //<suite-custom-code-autogenerated>
        protected Department()
        {

        }

        public Department(Guid id, DateTime date, string? code = null, string? name = null, string? note = null)
            : base(id, date, code, name, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}