using FaceAPI.Shared;
using FaceAPI.Titles;
using FaceAPI.Shared;
using FaceAPI.Titles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Departments;

namespace FaceAPI.Departments
{
    public class DepartmentsAppService : DepartmentsAppServiceBase, IDepartmentsAppService
    {
        //<suite-custom-code-autogenerated>
        public DepartmentsAppService(IDepartmentRepository departmentRepository, DepartmentManager departmentManager, IRepository<Title, Guid> titleRepository)
            : base(departmentRepository, departmentManager, titleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}