using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleFormats;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using FaceAPI.Shared;
using FaceAPI.ScheduleDetails;
using FaceAPI.Schedules;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.Timesheets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using FaceAPI.Shared;
using System.Net.Http;

namespace FaceAPI.Timesheets
{
    public class TimesheetsAppService : TimesheetsAppServiceBase, ITimesheetsAppService
    {
        //<suite-custom-code-autogenerated>
        public TimesheetsAppService(ITimesheetRepository timesheetRepository, TimesheetManager timesheetManager, IDistributedCache<TimesheetExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Schedule, Guid> scheduleRepository, IRepository<ScheduleDetail, Guid> scheduleDetailRepository, IRepository<ScheduleFormat, Guid> scheduleFormatRepository)
            : base(timesheetRepository, timesheetManager, excelDownloadTokenCache, scheduleRepository, scheduleDetailRepository, scheduleFormatRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}