using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.ScheduleDetails
{
    public class ScheduleDetailManager : ScheduleDetailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ScheduleDetailManager(IScheduleDetailRepository scheduleDetailRepository)
            : base(scheduleDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}