using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.ScheduleDetails
{
    public class ScheduleDetail : ScheduleDetailBase
    {
        //<suite-custom-code-autogenerated>
        protected ScheduleDetail()
        {

        }

        public ScheduleDetail(Guid id, DateTime fromDate, DateTime toDate, string? name = null, string? note = null)
            : base(id, fromDate, toDate, name, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}