using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using FaceAPI.Permissions;
using FaceAPI.ScheduleFormats;

namespace FaceAPI.ScheduleFormats
{
    public class ScheduleFormatsAppService : ScheduleFormatsAppServiceBase, IScheduleFormatsAppService
    {
        //<suite-custom-code-autogenerated>
        public ScheduleFormatsAppService(IScheduleFormatRepository scheduleFormatRepository, ScheduleFormatManager scheduleFormatManager)
            : base(scheduleFormatRepository, scheduleFormatManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}