using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace FaceAPI.ScheduleFormats
{
    public class ScheduleFormatManager : ScheduleFormatManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ScheduleFormatManager(IScheduleFormatRepository scheduleFormatRepository)
            : base(scheduleFormatRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}