using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace FaceAPI.ScheduleFormats
{
    public class ScheduleFormat : ScheduleFormatBase
    {
        //<suite-custom-code-autogenerated>
        protected ScheduleFormat()
        {

        }

        public ScheduleFormat(Guid id, DateTime date, int fromHours, int toHours, string? name = null, string? note = null)
            : base(id, date, fromHours, toHours, name, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}